name: Test tutorial and publish website

on:
  - push

jobs:
  test_tutorial:
    name: Check tutorial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11.11"
          activate-environment: claster-env

      - name: Create or update Conda environment from YAML
        shell: bash -el {0}
        run: |
          # Check if environment exists and update it if it does
          if conda env list | grep -q "claster-env"; then
            echo "Environment already exists, updating..."
            conda env update -f environment/claster-env.yml --prune
          else
            echo "Creating new environment..."
            conda env create -f environment/claster-env.yml
          fi

      - name: Install papermill
        shell: bash -el {0}
        run: |
          conda activate claster-env
          pip install papermill

      - name: Test Tutorial
        shell: bash -el {0}
        run: |
          conda activate claster-env
          cd scripts
          papermill 0_Tutorial.ipynb 0_Tutorial_out.ipynb -p epochs 4

  website:
    name: Publish notebooks as website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11.11"
          activate-environment: claster-env

      - name: Create or update Conda environment from YAML
        shell: bash -el {0}
        run: |
          # Check if environment exists and update it if it does
          if conda env list | grep -q "claster-env"; then
            echo "Environment already exists, updating..."
            conda env update -f environment/claster-env.yml --prune
          else
            echo "Creating new environment..."
            conda env create -f environment/claster-env.yml
          fi

      - name: Install website dependencies
        shell: bash -el {0}
        run: |
          conda activate claster-env
          pip install sphinx sphinx-book-theme myst-nb
          
      - name: Build website
        shell: bash -el {0}
        run: |
          conda activate claster-env
          sphinx-build -n --keep-going -b html ./ ./_build/
          
      - name: Publish workflow as website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
